# It shares both enviroment (dev and prod) and dockerfile. Don't include the port if it is different
services:
  express-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - ./.env
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
#    ports:
#      - 27017:27017
    env_file:
     - ./.mongo.env
    volumes:
     - mongo-db:/data/db

volumes:
  mongo-db:
